library(rJava)
library(tis)
.jinit()
.jaddClassPath(paste0(Sys.getenv("HOME"),"/Projects/TSDiff/out/artifacts/TSDiff_jar/TSDiff.jar"))
builder<-.jnew("com/oldfather/alfred/VintageListBuilder","GDPC1")
vlist<-.jcall(builder,"Lcom/oldfather/tsdiff/CompressedAlignedVintageList;","getVintageList")
vhead<-.jcall(vlist,"Lcom/oldfather/tsdiff/CompressedAlignedVintageNode;","getHead")
.jcall(vlist,"[D","getHeadSeries")
plot(vlist$getVintageSeries("2012-12-31"),type="l")
plot(vlist$getVintageSeries("2010-12-31"),type="l")
plot(vlist$getVintageSeries("2008-12-31"),type="l")
plot(vlist$getVintageSeries("2006-12-31"),type="l")
plot(vlist$getVintageSeries("2004-12-31"),type="l")
plot(vlist$getVintageSeries("2002-12-31"),type="l")
plot(vlist$getVintageSeries("2000-12-31"),type="l")

install.packages("tis")
